apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-assignment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-assignment
  template:
    metadata:
      labels:
        app: docker-assignment
    spec:
      containers:
      - name: democontainer1
        image: khanrehan12/docker-assignment:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9696
