apiVersion: v1
kind: Service
metadata:
  name: docker-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    tag: docker-assignment
  ports:
    - name: docker-assignment
      protocol: TCP
      port: 9696
      targetPort: 9696