apiVersion: v1
kind: Service
metadata:
  name: docker-service
spec:
  type: NodePort
  selector:
    app: dockerassignment
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
      nodePort: 30007
