apiVersion: v1
kind: Service
metadata:
  name: docker-assignment
spec:
  type: NodePort
  selector:
    app: docker-assignment
  ports:
    - protocol: TCP
      port: 9696
      targetPort: 9696
      nodePort: 30007
